name:  "sengrep"
on:
  workflow_dispatch:
jobs:
  semgrep:
    name:  "analyse semgrep"
    runs-on:  ubuntu-latest
    container:
      image:  returntocorp/semgrep:1.1.0
    steps:
      - name:  "checkout source"
        uses:   actions/checkout@v3
      - name:  "execute semgrep"
        run:  semgrep ci
        env:
          SEMGREP_RULES:  p/default 

        